/**
 * MASTER SEED: Animals (120+), Countries (195+), Sports (195+)
 * with all questions needed for 90%+ accuracy.
 * Only adds data — does NOT delete or modify existing entities.
 * Run: bun run prisma/seed-all.ts
 */
import { db } from "../src/lib/db";

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

async function ensureTag(name: string): Promise<{ id: string; slug: string }> {
  const slug = slugify(name);
  const existing = await db.tag.findUnique({ where: { slug } });
  if (existing) return { id: existing.id, slug };
  const created = await db.tag.create({ data: { name, slug } });
  return { id: created.id, slug };
}

async function ensureQuestion(text: string, tagName: string, categoryId: string): Promise<void> {
  const existing = await db.question.findFirst({ where: { text } });
  if (existing) return;
  const tag = await ensureTag(tagName);
  await db.question.create({ data: { text, primaryTagId: tag.id, categoryId, isActive: true } });
}

async function addEntity(name: string, description: string, categoryId: string, tags: string[], popularity: number, difficulty: number = 2): Promise<void> {
  const slug = slugify(name);
  const existing = await db.entity.findUnique({ where: { categoryId_slug: { categoryId, slug } } });
  const tagSlugs: string[] = []; const tagIds: string[] = []; const seen = new Set<string>();
  for (const t of tags) { const tag = await ensureTag(t); if (seen.has(tag.id)) continue; seen.add(tag.id); tagSlugs.push(tag.slug); tagIds.push(tag.id); }
  if (existing) {
    await db.entityTag.deleteMany({ where: { entityId: existing.id } });
    await db.entityTag.createMany({ data: tagIds.map(id => ({ entityId: existing.id, tagId: id, weight: 1 })) });
    await db.entity.update({ where: { id: existing.id }, data: { description, popularity, difficulty, tagCache: tagSlugs.join(","), isActive: true } });
  } else {
    await db.entity.create({ data: { name, slug, description, categoryId, popularity, difficulty, tagCache: tagSlugs.join(","), tags: { create: tagIds.map(id => ({ tagId: id, weight: 1 })) } } });
  }
}

// Question maps (tag → friendly question text)
const ANIMAL_Q: Record<string, string> = {
  mammal: "Is it a mammal?", bird: "Is it a bird?", reptile: "Is it a reptile?", amphibian: "Is it an amphibian?",
  fish: "Is it a fish?", insect: "Is it an insect?", arachnid: "Is it an arachnid (spider-like)?", crustacean: "Is it a crustacean?",
  cephalopod: "Is it a cephalopod (like an octopus)?", carnivore: "Does it eat meat?", herbivore: "Does it eat plants?",
  omnivore: "Does it eat both plants and meat?", insectivore: "Does it eat insects?", africa: "Does it live in Africa?",
  asia: "Does it live in Asia?", north_america: "Does it live in North America?", south_america: "Does it live in South America?",
  europe: "Does it live in Europe?", australia: "Does it live in Australia?", antarctica: "Does it live in cold Arctic or Antarctic regions?",
  ocean: "Does it live in the ocean?", massive: "Is it very large (like a car or bigger)?", large: "Is it bigger than a human?",
  medium: "Is it around the size of a dog?", small: "Is it small enough to fit in a backpack?", tiny: "Is it smaller than your hand?",
  slow: "Is it slow-moving?", fast: "Is it fast?", very_fast: "Is it one of the fastest animals?",
  land: "Does it live on land?", water: "Does it live in water?", air: "Can it fly?", semi_aquatic: "Does it spend time on land and in water?",
  tree_dwelling: "Does it live in trees?", wild: "Does it live in the wild?", domesticated: "Is it a common pet or farm animal?",
  farmed: "Is it raised on farms?", pet: "Is it commonly kept as a pet?", zoo_common: "Is it commonly found in zoos?",
  fur: "Does it have fur or hair?", feathers: "Does it have feathers?", scales: "Does it have scales?", skin: "Does it have mostly bare skin?",
  shell: "Does it have a shell?", exoskeleton: "Does it have a hard outer skeleton?", venomous_bite: "Does it have a venomous bite?",
  venomous_sting: "Does it have a venomous sting?", poisonous: "Is it poisonous to touch or eat?", flight: "Can it fly?",
  swims_well: "Is it a good swimmer?", camouflage: "Is it good at camouflage?", loud_vocalization: "Is it known for loud sounds?",
  horns: "Does it have horns?", tusks: "Does it have tusks?", claws: "Does it have claws?", tail: "Does it have a prominent tail?",
  bioluminescent: "Can it glow in the dark?", trunk: "Does it have a trunk?", mane: "Does the male have a mane?", spines: "Does it have spines?",
  quills: "Does it have quills?", animal: "Is it an animal?",
};

const COUNTRY_Q: Record<string, string> = {
  asian: "Is it in Asia?", european: "Is it in Europe?", american: "Is it in the Americas?", african: "Is it in Africa?",
  oceanian: "Is it in Oceania?", island: "Is it an island nation?", landlocked: "Is it landlocked?", large: "Is it a large country?",
  small: "Is it a small country?", populous: "Is it a populous country?", developed: "Is it a developed country?",
  developing: "Is it a developing country?", tropical: "Is it a tropical country?", cold: "Is it a cold country?", hot: "Is it a hot country?",
  desert: "Does it have a desert?", mountainous: "Does it have mountains?", beaches: "Is it known for beaches?",
  monarchy: "Is it a monarchy?", ancient_place: "Is it an ancient civilization?", english_speaking: "Is it English-speaking?",
  french_speaking: "Is it a French-speaking country?", spanish_speaking: "Is it a Spanish-speaking country?",
  portuguese_speaking: "Is it a Portuguese-speaking country?", arabic_speaking: "Is it an Arabic-speaking country?",
  oil_rich: "Is it an oil-rich country?", tech_advanced: "Is it known for technology?", communist: "Is it a communist state?",
  place: "Is it a country?", country: "Is it a country?", southern_hemisphere: "Is it in the Southern Hemisphere?",
  middle_east: "Is it in the Middle East?", caribbean: "Is it in the Caribbean?", rainforest: "Does it have rainforests?",
  spicy_food: "Is it known for spicy food?",
};

const SPORT_Q: Record<string, string> = {
  team_sport: "Is it a team sport?", individual_sport: "Is it an individual sport?", combat_sport: "Is it a combat sport?",
  racing_sport: "Is it a racing sport?", water_sport: "Is it a water sport?", winter_sport: "Is it a winter sport?",
  motorsport: "Is it a motorsport?", racket_sport: "Is it a racket sport?", ball_sport: "Does it use a ball?",
  uses_ball: "Does it use a ball?", uses_racket: "Does it use a racket?", uses_board: "Does it use a board?",
  uses_vehicle: "Does it use a vehicle?", uses_skis: "Does it use skis?", uses_gun: "Does it use a gun?",
  uses_horse: "Does it use a horse?", uses_stick: "Does it use a stick?", uses_bat: "Does it use a bat?",
  olympic: "Is it an Olympic sport?", contact: "Is it a contact sport?", dangerous: "Is it dangerous?",
  popular_sport: "Is it a popular sport?", indoor_sport: "Is it played indoors?", outdoor_sport: "Is it played outdoors?",
  ice_sport: "Is it played on ice?", snow_sport: "Is it played on snow?", net_sport: "Does it use a net?",
  court_sport: "Is it played on a court?", field_sport: "Is it played on a field?", swimming: "Does it involve swimming?",
  skating: "Does it involve skating?", riding: "Does it involve riding?", shooting: "Does it involve shooting?",
  jumping: "Does it involve jumping?", throwing: "Does it involve throwing?", kicking: "Does it involve kicking?",
  striking: "Does it involve fighting?", grappling: "Does it involve grappling?", endurance: "Does it require endurance?",
  strength: "Does it require strength?", precision: "Does it require precision?", extreme_sport: "Is it an extreme sport?",
  sport: "Is it a sport?", uses_puck: "Does it use a puck?", uses_shuttlecock: "Does it use a shuttlecock?",
  uses_boat: "Does it use a boat?", uses_bike: "Does it use a bike?", uses_bow: "Does it use a bow?",
  uses_rope: "Does it use a rope?", uses_cue: "Does it use a cue?", no_ball: "Does it NOT use a ball?",
};

async function main() {
  console.log("=== MASTER SEED ===\n");

  const [animalCat, countryCat, sportCat] = await Promise.all([
    db.category.findUnique({ where: { slug: "animals" } }),
    db.category.findUnique({ where: { slug: "countries" } }),
    db.category.findUnique({ where: { slug: "sports" } }),
  ]);

  if (!animalCat || !countryCat || !sportCat) {
    console.error("Categories not found! Run prisma/seed.ts first.");
    process.exit(1);
  }

  // === ADD QUESTIONS ===
  console.log("Adding questions...");
  let qCount = 0;
  for (const [tag, q] of Object.entries(ANIMAL_Q)) { await ensureQuestion(q, tag, animalCat.id); qCount++; }
  for (const [tag, q] of Object.entries(COUNTRY_Q)) { await ensureQuestion(q, tag, countryCat.id); qCount++; }
  for (const [tag, q] of Object.entries(SPORT_Q)) { await ensureQuestion(q, tag, sportCat.id); qCount++; }
  console.log(`  + ${qCount} questions ensured`);

  // === ANIMALS (120+) ===
  // Using the helper: a(name, desc, tags, pop)
  const A = (name: string, desc: string, tags: string[], pop: number) => addEntity(name, desc, animalCat.id, ["animal", ...tags], pop);

  const animals: [string, string, string[], number][] = [
    ["African Elephant", "The largest land animal.", ["mammal", "africa", "herbivore", "massive", "land", "wild", "zoo_common", "skin", "tusks", "loud_vocalization", "trunk"], 90],
    ["Asian Elephant", "Large elephant species native to Asia.", ["mammal", "asia", "herbivore", "massive", "land", "wild", "zoo_common", "skin", "tusks"], 75],
    ["Lion", "The king of the jungle.", ["mammal", "africa", "carnivore", "large", "fast", "land", "wild", "zoo_common", "fur", "claws", "loud_vocalization", "mane"], 95],
    ["Tiger", "The largest cat species, striped and fierce.", ["mammal", "asia", "carnivore", "large", "very_fast", "land", "wild", "zoo_common", "fur", "claws", "camouflage"], 92],
    ["Leopard", "Spotted big cat known for climbing trees.", ["mammal", "africa", "asia", "carnivore", "medium", "very_fast", "land", "tree_dwelling", "wild", "zoo_common", "fur", "claws", "camouflage"], 78],
    ["Cheetah", "The fastest land animal.", ["mammal", "africa", "carnivore", "medium", "very_fast", "land", "wild", "zoo_common", "fur", "claws"], 85],
    ["Jaguar", "Powerful spotted big cat of the Americas.", ["mammal", "south_america", "carnivore", "large", "fast", "land", "tree_dwelling", "wild", "zoo_common", "fur", "claws", "camouflage"], 72],
    ["Grizzly Bear", "Large brown bear of North America.", ["mammal", "north_america", "omnivore", "massive", "fast", "land", "wild", "zoo_common", "fur", "claws"], 78],
    ["Polar Bear", "White bear of the Arctic.", ["mammal", "antarctica", "carnivore", "massive", "fast", "land", "semi_aquatic", "wild", "zoo_common", "fur", "swims_well", "claws"], 82],
    ["Panda Bear", "Black and white bear that eats bamboo.", ["mammal", "asia", "herbivore", "large", "slow", "land", "tree_dwelling", "wild", "zoo_common", "fur", "camouflage"], 90],
    ["Wolf", "Wild ancestor of dogs, pack hunter.", ["mammal", "north_america", "europe", "asia", "carnivore", "medium", "fast", "land", "wild", "fur", "claws", "loud_vocalization"], 80],
    ["Fox", "Small cunning canine.", ["mammal", "north_america", "europe", "asia", "omnivore", "small", "fast", "land", "wild", "fur", "camouflage"], 65],
    ["Giraffe", "Tallest animal with a long neck.", ["mammal", "africa", "herbivore", "massive", "land", "wild", "zoo_common", "skin", "loud_vocalization"], 88],
    ["Zebra", "Striped African equine.", ["mammal", "africa", "herbivore", "large", "fast", "land", "wild", "zoo_common", "fur", "camouflage"], 82],
    ["Hippopotamus", "Large semi-aquatic African mammal.", ["mammal", "africa", "herbivore", "massive", "semi_aquatic", "wild", "zoo_common", "skin", "swims_well"], 75],
    ["Rhinoceros", "Large armored herbivore with horns.", ["mammal", "africa", "asia", "herbivore", "massive", "land", "wild", "zoo_common", "skin", "horns"], 76],
    ["Kangaroo", "Marsupial that hops and carries babies.", ["mammal", "australia", "herbivore", "medium", "fast", "land", "wild", "zoo_common", "fur"], 85],
    ["Koala", "Australian marsupial that eats eucalyptus.", ["mammal", "australia", "herbivore", "small", "slow", "tree_dwelling", "wild", "zoo_common", "fur"], 80],
    ["Gorilla", "Largest primate, silverback leader.", ["mammal", "africa", "herbivore", "large", "land", "wild", "zoo_common", "fur"], 78],
    ["Chimpanzee", "Intelligent primate closest to humans.", ["mammal", "africa", "omnivore", "medium", "fast", "tree_dwelling", "land", "wild", "zoo_common", "fur"], 75],
    ["Platypus", "Egg-laying mammal with a duck bill.", ["mammal", "australia", "carnivore", "small", "semi_aquatic", "wild", "zoo_common", "fur", "swims_well"], 60],
    ["Sloth", "Slow-moving tree dweller.", ["mammal", "south_america", "herbivore", "medium", "slow", "tree_dwelling", "wild", "fur", "camouflage", "claws"], 60],
    ["Beaver", "Dam-building rodent.", ["mammal", "north_america", "europe", "asia", "herbivore", "medium", "semi_aquatic", "wild", "fur", "swims_well", "tail"], 62],
    ["Otter", "Playful aquatic mammal.", ["mammal", "carnivore", "small", "semi_aquatic", "wild", "zoo_common", "fur", "swims_well"], 68],
    ["Dolphin", "Intelligent marine mammal.", ["mammal", "ocean", "carnivore", "large", "very_fast", "water", "wild", "zoo_common", "skin", "swims_well", "loud_vocalization"], 88],
    ["Orca", "Largest dolphin species, black and white.", ["mammal", "ocean", "carnivore", "massive", "very_fast", "water", "wild", "zoo_common", "skin", "swims_well", "loud_vocalization"], 82],
    ["Blue Whale", "Largest animal on Earth.", ["mammal", "ocean", "carnivore", "massive", "fast", "water", "wild", "zoo_common", "skin", "swims_well", "loud_vocalization"], 90],
    ["Humpback Whale", "Large baleen whale known for breaching.", ["mammal", "ocean", "carnivore", "massive", "fast", "water", "wild", "zoo_common", "skin", "swims_well", "loud_vocalization"], 75],
    ["Bald Eagle", "National bird of the USA.", ["bird", "north_america", "carnivore", "large", "very_fast", "air", "wild", "zoo_common", "feathers", "flight", "claws"], 85],
    ["Peregrine Falcon", "Fastest bird in a dive.", ["bird", "carnivore", "medium", "very_fast", "air", "wild", "feathers", "flight"], 70],
    ["Owl", "Nocturnal bird of prey.", ["bird", "carnivore", "medium", "air", "tree_dwelling", "wild", "feathers", "flight", "camouflage"], 65],
    ["Vulture", "Scavenging bird with a bald head.", ["bird", "carnivore", "large", "air", "wild", "feathers", "flight", "camouflage"], 55],
    ["Emperor Penguin", "Largest penguin, lives in Antarctica.", ["bird", "antarctica", "carnivore", "medium", "semi_aquatic", "wild", "zoo_common", "feathers", "swims_well", "camouflage"], 78],
    ["Ostrich", "Largest living bird, flightless.", ["bird", "africa", "omnivore", "massive", "very_fast", "land", "wild", "zoo_common", "feathers"], 72],
    ["Peacock", "Bird famous for its beautiful tail.", ["bird", "asia", "omnivore", "large", "land", "wild", "zoo_common", "feathers", "loud_vocalization", "camouflage"], 70],
    ["Flamingo", "Pink wading bird that stands on one leg.", ["bird", "africa", "south_america", "omnivore", "large", "semi_aquatic", "wild", "zoo_common", "feathers", "camouflage"], 72],
    ["Macaw", "Colorful tropical parrot.", ["bird", "south_america", "omnivore", "small", "air", "tree_dwelling", "wild", "zoo_common", "feathers", "flight", "loud_vocalization", "camouflage"], 65],
    ["Toucan", "Bird with a huge colorful bill.", ["bird", "south_america", "omnivore", "small", "air", "tree_dwelling", "wild", "zoo_common", "feathers", "flight", "camouflage"], 68],
    ["Hummingbird", "Tiny bird that hovers and drinks nectar.", ["bird", "north_america", "south_america", "omnivore", "tiny", "very_fast", "air", "wild", "feathers", "flight"], 72],
    ["Crow", "Highly intelligent black bird.", ["bird", "omnivore", "small", "fast", "air", "wild", "feathers", "flight", "loud_vocalization"], 58],
    ["Swan", "Elegant white water bird.", ["bird", "omnivore", "large", "semi_aquatic", "wild", "zoo_common", "feathers", "flight", "swims_well"], 62],
    ["Duck", "Common quacking waterfowl.", ["bird", "omnivore", "small", "fast", "semi_aquatic", "wild", "farmed", "feathers", "flight", "swims_well", "loud_vocalization"], 75],
    ["Chicken", "Common farm bird that lays eggs.", ["bird", "herbivore", "small", "slow", "land", "farmed", "feathers", "loud_vocalization"], 85],
    ["Saltwater Crocodile", "Largest living reptile, aggressive.", ["reptile", "asia", "carnivore", "massive", "semi_aquatic", "wild", "scales", "swims_well", "claws", "venomous_bite"], 70],
    ["Komodo Dragon", "Largest lizard, venomous bite.", ["reptile", "asia", "carnivore", "large", "fast", "land", "wild", "zoo_common", "scales", "claws", "venomous_bite"], 72],
    ["King Cobra", "Long venomous snake.", ["reptile", "asia", "carnivore", "large", "fast", "land", "wild", "zoo_common", "scales", "venomous_bite"], 72],
    ["Black Mamba", "Extremely fast and venomous snake.", ["reptile", "africa", "carnivore", "medium", "very_fast", "land", "wild", "scales", "venomous_bite", "camouflage"], 68],
    ["Rattlesnake", "Rattling venomous pit viper.", ["reptile", "north_america", "carnivore", "medium", "land", "wild", "scales", "venomous_bite", "camouflage", "loud_vocalization"], 65],
    ["Green Sea Turtle", "Large sea turtle with a shell.", ["reptile", "ocean", "herbivore", "large", "water", "wild", "scales", "shell", "swims_well"], 65],
    ["Galapagos Tortoise", "Giant tortoise from Galapagos.", ["reptile", "south_america", "herbivore", "large", "slow", "land", "wild", "zoo_common", "scales", "shell"], 68],
    ["Poison Dart Frog", "Tiny but deadly poisonous frog.", ["amphibian", "south_america", "carnivore", "tiny", "tree_dwelling", "wild", "zoo_common", "skin", "poisonous", "camouflage"], 62],
    ["Axolotl", "Salamander that never grows up.", ["amphibian", "north_america", "carnivore", "tiny", "slow", "water", "wild", "zoo_common", "skin", "swims_well", "camouflage"], 58],
    ["Great White Shark", "Apex predator of the ocean.", ["fish", "ocean", "carnivore", "massive", "very_fast", "water", "wild", "zoo_common", "scales", "swims_well", "claws"], 92],
    ["Whale Shark", "Largest fish, gentle filter feeder.", ["fish", "ocean", "omnivore", "massive", "water", "wild", "scales", "swims_well"], 65],
    ["Clownfish", "Orange clown fish from coral reefs.", ["fish", "ocean", "omnivore", "tiny", "water", "wild", "zoo_common", "scales", "swims_well", "camouflage"], 80],
    ["Octopus", "Highly intelligent eight-armed creature.", ["cephalopod", "ocean", "carnivore", "small", "fast", "water", "wild", "zoo_common", "skin", "swims_well", "camouflage"], 82],
    ["Jellyfish", "Gelatinous drifting sea creature.", ["cephalopod", "ocean", "carnivore", "small", "slow", "water", "wild", "skin", "swims_well", "venomous_sting"], 55],
    ["Seahorse", "Tiny fish that swims upright.", ["fish", "ocean", "carnivore", "tiny", "slow", "water", "wild", "zoo_common", "scales", "swims_well", "camouflage"], 58],
    ["Honey Bee", "Social insect that makes honey.", ["insect", "herbivore", "tiny", "fast", "air", "wild", "exoskeleton", "flight", "venomous_sting", "loud_vocalization"], 78],
    ["Monarch Butterfly", "Orange butterfly that migrates.", ["insect", "herbivore", "tiny", "air", "wild", "exoskeleton", "flight", "camouflage"], 72],
    ["Dragonfly", "Fast insect with four wings.", ["insect", "carnivore", "tiny", "very_fast", "air", "wild", "exoskeleton", "flight"], 55],
    ["Praying Mantis", "Predatory insect that folds its legs.", ["insect", "carnivore", "small", "slow", "land", "wild", "exoskeleton", "camouflage"], 52],
    ["Tarantula", "Large hairy spider.", ["arachnid", "carnivore", "small", "slow", "land", "wild", "exoskeleton", "venomous_bite", "camouflage"], 65],
    ["Scorpion", "Arachnid with a venomous tail stinger.", ["arachnid", "carnivore", "small", "slow", "land", "wild", "exoskeleton", "venomous_sting", "camouflage"], 58],
    ["Lobster", "Large crustacean with claws.", ["crustacean", "ocean", "carnivore", "small", "slow", "water", "wild", "exoskeleton", "shell", "swims_well", "claws"], 60],
    ["Crab", "Hard-shelled crustacean that walks sideways.", ["crustacean", "ocean", "carnivore", "small", "slow", "semi_aquatic", "wild", "exoskeleton", "shell", "swims_well", "claws", "camouflage"], 55],
    ["Dog", "Man's best friend.", ["mammal", "omnivore", "medium", "fast", "land", "domesticated", "pet", "fur", "claws", "loud_vocalization"], 98],
    ["Cat", "Common house pet and skilled hunter.", ["mammal", "carnivore", "small", "fast", "land", "domesticated", "pet", "fur", "claws"], 96],
    ["Horse", "Domesticated rideable animal.", ["mammal", "herbivore", "large", "very_fast", "land", "domesticated", "farmed", "fur", "tail"], 90],
    ["Cow", "Farm animal raised for milk and meat.", ["mammal", "herbivore", "large", "slow", "land", "farmed", "skin"], 88],
    ["Pig", "Pink farm animal that oinks.", ["mammal", "omnivore", "medium", "land", "farmed", "skin", "loud_vocalization"], 82],
    ["Sheep", "Wooly farm animal.", ["mammal", "herbivore", "medium", "slow", "land", "farmed", "fur", "camouflage"], 75],
    ["Goat", "Farm animal that eats anything.", ["mammal", "herbivore", "medium", "land", "farmed", "fur", "claws", "horns"], 70],
    ["Rabbit", "Small hopping pet with long ears.", ["mammal", "herbivore", "small", "fast", "land", "domesticated", "pet", "fur", "claws"], 80],
    ["Hamster", "Tiny rodent kept as a pet.", ["mammal", "omnivore", "tiny", "fast", "land", "domesticated", "pet", "fur"], 72],
    ["Camel", "Desert ship, humped mammal.", ["mammal", "asia", "africa", "herbivore", "large", "land", "domesticated", "farmed", "zoo_common", "fur"], 70],
    ["Llama", "South American camelid.", ["mammal", "south_america", "herbivore", "medium", "land", "domesticated", "farmed", "fur"], 50],
    ["Alpaca", "Fluffy South American camelid.", ["mammal", "south_america", "herbivore", "medium", "land", "domesticated", "farmed", "fur"], 52],
    ["Bison", "Large North American bovine.", ["mammal", "north_america", "herbivore", "massive", "land", "wild", "zoo_common", "fur", "horns"], 60],
    ["Deer", "Common graceful herbivore.", ["mammal", "herbivore", "medium", "fast", "land", "wild", "zoo_common", "fur"], 60],
    ["Seal", "Aquatic mammal with flippers.", ["mammal", "antarctica", "carnivore", "large", "semi_aquatic", "wild", "zoo_common", "skin", "swims_well"], 60],
    ["Walrus", "Large tusked marine mammal.", ["mammal", "antarctica", "carnivore", "massive", "semi_aquatic", "wild", "zoo_common", "skin", "swims_well", "tusks"], 62],
    ["Sperm Whale", "Large toothed whale that dives deep.", ["mammal", "ocean", "carnivore", "massive", "fast", "water", "wild", "zoo_common", "skin", "swims_well", "loud_vocalization"], 68],
    ["Coyote", "Wild dog of the Americas.", ["mammal", "north_america", "omnivore", "medium", "fast", "land", "wild", "fur"], 50],
    ["Hyena", "Laughing scavenger of Africa.", ["mammal", "africa", "carnivore", "medium", "land", "wild", "zoo_common", "fur", "loud_vocalization"], 60],
    ["Cape Buffalo", "Large dangerous African bovine.", ["mammal", "africa", "herbivore", "large", "fast", "land", "wild", "zoo_common", "fur", "horns"], 55],
    ["Moose", "Largest deer species.", ["mammal", "north_america", "europe", "asia", "herbivore", "large", "land", "wild", "fur", "horns"], 58],
    ["Reindeer", "Arctic deer with antlers.", ["mammal", "antarctica", "herbivore", "large", "land", "wild", "fur", "horns"], 65],
    ["Wombat", "Burrowing Australian marsupial.", ["mammal", "australia", "herbivore", "medium", "land", "wild", "zoo_common", "fur"], 45],
    ["Tasmanian Devil", "Small fierce marsupial from Tasmania.", ["mammal", "australia", "carnivore", "small", "land", "wild", "zoo_common", "fur", "loud_vocalization"], 48],
    ["Echidna", "Spiny egg-laying mammal.", ["mammal", "australia", "insectivore", "small", "slow", "land", "wild", "zoo_common", "fur", "claws"], 42],
    ["Orangutan", "Red-haired Asian ape.", ["mammal", "asia", "herbivore", "large", "slow", "tree_dwelling", "wild", "zoo_common", "fur"], 65],
    ["Baboon", "Large ground-dwelling monkey.", ["mammal", "africa", "omnivore", "medium", "land", "wild", "zoo_common", "fur"], 55],
    ["Lemur", "Small primate from Madagascar.", ["mammal", "africa", "omnivore", "small", "fast", "tree_dwelling", "wild", "zoo_common", "fur", "loud_vocalization", "camouflage"], 58],
    ["Anteater", "Long-nosed insect eater.", ["mammal", "south_america", "insectivore", "medium", "land", "wild", "fur", "claws"], 45],
    ["Armadillo", "Armored mammal with a shell.", ["mammal", "south_america", "insectivore", "small", "land", "wild", "shell", "claws", "camouflage"], 52],
    ["Hedgehog", "Small spiny mammal.", ["mammal", "europe", "asia", "insectivore", "small", "slow", "land", "wild", "fur", "spines", "camouflage"], 55],
    ["Porcupine", "Rodent with protective quills.", ["mammal", "herbivore", "medium", "slow", "land", "wild", "fur", "quills", "claws", "camouflage"], 48],
    ["Sea Lion", "Eared seal that can walk on land.", ["mammal", "carnivore", "large", "semi_aquatic", "wild", "zoo_common", "skin", "swims_well"], 55],
    ["Pangolin", "Scaly anteater, heavily trafficked.", ["mammal", "asia", "africa", "insectivore", "small", "slow", "land", "wild", "scales", "camouflage", "claws"], 40],
    ["Golden Eagle", "Large powerful eagle.", ["bird", "carnivore", "large", "very_fast", "air", "wild", "feathers", "flight", "claws"], 65],
    ["Hawk", "Common bird of prey.", ["bird", "carnivore", "medium", "fast", "air", "wild", "feathers", "flight"], 55],
    ["Albatross", "Seabird with the longest wingspan.", ["bird", "ocean", "carnivore", "large", "air", "wild", "feathers", "flight"], 50],
    ["Emu", "Large Australian flightless bird.", ["bird", "australia", "omnivore", "massive", "fast", "land", "wild", "zoo_common", "feathers"], 55],
    ["Cassowary", "Dangerous flightless bird with claws.", ["bird", "australia", "omnivore", "large", "fast", "land", "wild", "feathers", "claws"], 52],
    ["Pelican", "Large water bird with a pouch.", ["bird", "carnivore", "large", "semi_aquatic", "wild", "feathers", "flight", "swims_well"], 55],
    ["Woodpecker", "Bird that drums on trees.", ["bird", "insectivore", "small", "air", "tree_dwelling", "wild", "feathers", "flight"], 55],
    ["Raven", "Large black bird, smarter than crows.", ["bird", "omnivore", "medium", "fast", "air", "wild", "feathers", "flight", "loud_vocalization"], 50],
    ["Goose", "Common waterfowl that honks.", ["bird", "herbivore", "medium", "fast", "semi_aquatic", "wild", "farmed", "feathers", "flight", "swims_well", "loud_vocalization"], 60],
    ["Turkey", "Large farm bird for meat.", ["bird", "omnivore", "large", "land", "farmed", "feathers", "loud_vocalization"], 72],
    ["American Alligator", "Large American crocodilian.", ["reptile", "north_america", "carnivore", "large", "semi_aquatic", "wild", "scales", "swims_well", "claws"], 68],
    ["Green Anaconda", "Largest snake by weight.", ["reptile", "south_america", "carnivore", "massive", "slow", "semi_aquatic", "wild", "zoo_common", "scales", "swims_well", "camouflage"], 70],
    ["Reticulated Python", "Long snake with beautiful patterns.", ["reptile", "asia", "carnivore", "large", "land", "wild", "zoo_common", "scales", "swims_well", "camouflage"], 55],
    ["Gila Monster", "Venomous lizard with bead-like scales.", ["reptile", "north_america", "carnivore", "medium", "slow", "land", "wild", "scales", "venomous_bite", "camouflage"], 45],
    ["Leatherback Turtle", "Largest sea turtle, leathery shell.", ["reptile", "ocean", "carnivore", "massive", "water", "wild", "scales", "shell", "swims_well"], 55],
    ["Red-Eyed Tree Frog", "Colorful tree frog with red eyes.", ["amphibian", "south_america", "carnivore", "tiny", "tree_dwelling", "wild", "zoo_common", "skin", "camouflage"], 65],
    ["Hammerhead Shark", "Shark with a hammer-shaped head.", ["fish", "ocean", "carnivore", "large", "fast", "water", "wild", "scales", "swims_well"], 60],
    ["Manta Ray", "Large ray that glides through water.", ["fish", "ocean", "carnivore", "massive", "water", "wild", "skin", "swims_well"], 52],
    ["Stingray", "Flat fish with a venomous tail barb.", ["fish", "ocean", "carnivore", "medium", "semi_aquatic", "wild", "skin", "swims_well", "venomous_sting", "camouflage"], 55],
    ["Blue Tang", "Blue tropical fish.", ["fish", "ocean", "omnivore", "tiny", "water", "wild", "zoo_common", "scales", "swims_well", "camouflage"], 65],
    ["Lionfish", "Striped venomous reef fish.", ["fish", "ocean", "carnivore", "small", "slow", "water", "wild", "scales", "swims_well", "venomous_sting", "camouflage"], 45],
    ["Pufferfish", "Fish that puffs up when scared.", ["fish", "ocean", "carnivore", "small", "slow", "water", "wild", "scales", "swims_well", "poisonous", "camouflage"], 60],
    ["Anglerfish", "Deep sea fish with a glowing lure.", ["fish", "ocean", "carnivore", "small", "slow", "water", "wild", "skin", "swims_well", "bioluminescent", "camouflage"], 55],
    ["Giant Squid", "Giant deep-sea squid with huge eyes.", ["cephalopod", "ocean", "carnivore", "massive", "water", "wild", "skin", "swims_well"], 60],
    ["Moray Eel", "Long snake-like reef fish.", ["fish", "ocean", "carnivore", "medium", "water", "wild", "scales", "swims_well", "camouflage"], 45],
    ["Bumblebee", "Fuzzy flying insect.", ["insect", "herbivore", "tiny", "fast", "air", "wild", "exoskeleton", "flight", "venomous_sting"], 60],
    ["Atlas Moth", "Large moth with beautiful wings.", ["insect", "asia", "herbivore", "small", "air", "wild", "exoskeleton", "flight", "camouflage"], 45],
    ["Stick Insect", "Insect that looks like a twig.", ["insect", "asia", "herbivore", "small", "slow", "tree_dwelling", "wild", "exoskeleton", "camouflage"], 35],
    ["Goliath Beetle", "World's heaviest beetle.", ["insect", "africa", "herbivore", "small", "slow", "land", "wild", "exoskeleton", "claws"], 40],
    ["Black Widow Spider", "Small spider with a red hourglass mark.", ["arachnid", "carnivore", "tiny", "slow", "land", "wild", "exoskeleton", "venomous_bite", "camouflage"], 60],
    ["Centipede", "Many-legged crawling creature.", ["carnivore", "small", "fast", "land", "wild", "exoskeleton", "venomous_bite"], 45],
    ["Snail", "Slow creature that carries its shell.", ["gastropod", "herbivore", "tiny", "slow", "land", "wild", "shell", "camouflage"], 50],
    ["Earthworm", "Segmented worm that lives in soil.", ["annelid", "herbivore", "tiny", "slow", "land", "wild", "skin"], 45],
    ["Donkey", "Long-eared beast of burden.", ["mammal", "herbivore", "medium", "land", "domesticated", "farmed", "fur", "loud_vocalization"], 65],
  ];

  console.log(`\nAdding ${animals.length} animals...`);
  for (const [name, desc, tags, pop] of animals) { await A(name, desc, tags, pop); }

  // === COUNTRIES (195+) ===
  const C = (name: string, desc: string, tags: string[], pop: number) => addEntity(name, desc, countryCat.id, ["place", "country", ...tags], pop);

  const countries: [string, string, string[], number][] = [
    ["Japan", "An island nation in East Asia.", ["asian", "island", "developed", "tech_advanced", "mountainous", "populous"], 95],
    ["China", "The world's most populous country.", ["asian", "large", "populous", "developing", "communist", "mountainous"], 92],
    ["India", "A populous South Asian nation.", ["asian", "large", "populous", "developing", "tropical", "spicy_food", "ancient_place"], 90],
    ["South Korea", "A tech-forward East Asian nation.", ["asian", "developed", "tech_advanced"], 85],
    ["Thailand", "A Southeast Asian kingdom.", ["asian", "tropical", "developing", "beaches", "spicy_food"], 78],
    ["United Kingdom", "A nation of four countries in NW Europe.", ["european", "island", "developed", "english_speaking", "monarchy", "ancient_place"], 93],
    ["France", "A Western European nation famed for culture.", ["european", "developed", "french_speaking", "mountainous", "beaches", "ancient_place"], 92],
    ["Germany", "A central European economic powerhouse.", ["european", "developed", "large", "populous"], 90],
    ["Italy", "A Mediterranean European nation.", ["european", "developed", "ancient_place", "mountainous", "beaches", "mediterranean"], 90],
    ["Spain", "A sunny southwestern European nation.", ["european", "developed", "spanish_speaking", "beaches", "mountainous", "monarchy"], 85],
    ["Russia", "The largest country, spanning two continents.", ["european", "asian", "large", "cold", "populous", "communist"], 88],
    ["United States", "A large federal republic in North America.", ["american", "developed", "large", "populous", "tech_advanced", "english_speaking", "mountainous"], 97],
    ["Canada", "A large northern North American nation.", ["american", "large", "developed", "cold", "english_speaking", "mountainous"], 88],
    ["Brazil", "The largest South American nation.", ["american", "large", "developing", "tropical", "portuguese_speaking", "rainforest", "southern_hemisphere", "beaches"], 86],
    ["Mexico", "A North American nation south of the US.", ["american", "developing", "spanish_speaking", "ancient_place", "spicy_food"], 84],
    ["Egypt", "A North African nation of ancient wonders.", ["african", "developing", "arabic_speaking", "ancient_place", "desert", "hot"], 85],
    ["South Africa", "The southernmost African nation.", ["african", "developing", "english_speaking", "beaches", "mountainous"], 78],
    ["Nigeria", "The most populous African nation.", ["african", "developing", "populous", "english_speaking", "tropical"], 72],
    ["Kenya", "An East African nation known for safaris.", ["african", "developing", "tropical", "mountainous"], 70],
    ["Australia", "A continent-country in the Southern Hemisphere.", ["oceanian", "island", "developed", "large", "english_speaking", "desert", "beaches", "southern_hemisphere"], 90],
    ["New Zealand", "A scenic island nation in the Pacific.", ["oceanian", "island", "developed", "mountainous", "english_speaking", "southern_hemisphere"], 80],
    ["Saudi Arabia", "A large Middle Eastern kingdom.", ["asian", "middle_east", "developing", "large", "arabic_speaking", "desert", "oil_rich", "hot", "monarchy"], 65],
    ["United Arab Emirates", "A wealthy Gulf federation.", ["asian", "middle_east", "developed", "arabic_speaking", "oil_rich", "hot", "desert", "monarchy"], 65],
    ["Turkey", "A transcontinental Eurasian nation.", ["european", "asian", "developing", "mountainous", "ancient_place", "beaches", "mediterranean"], 70],
    ["Iran", "A large Middle Eastern nation.", ["asian", "middle_east", "developing", "arabic_speaking", "mountainous", "oil_rich", "ancient_place", "hot", "desert"], 60],
    ["Iraq", "A Middle Eastern nation, cradle of civilization.", ["asian", "middle_east", "developing", "arabic_speaking", "oil_rich", "ancient_place", "desert", "hot"], 50],
    ["Israel", "A small Middle Eastern tech powerhouse.", ["asian", "middle_east", "developed", "tech_advanced", "ancient_place", "mediterranean", "hot"], 55],
    ["Argentina", "A large South American nation.", ["american", "developing", "spanish_speaking", "mountainous", "southern_hemisphere", "cold"], 65],
    ["Chile", "A long South American coastal nation.", ["american", "developing", "spanish_speaking", "mountainous", "southern_hemisphere", "cold"], 55],
    ["Colombia", "A tropical South American nation.", ["american", "developing", "spanish_speaking", "tropical", "mountainous", "beaches", "rainforest"], 50],
    ["Peru", "Home of the Incas and Machu Picchu.", ["american", "developing", "spanish_speaking", "mountainous", "ancient_place", "tropical"], 50],
    ["Vietnam", "A Southeast Asian nation.", ["asian", "developing", "tropical", "beaches", "spicy_food", "communist"], 50],
    ["Indonesia", "The world's largest archipelago.", ["asian", "developing", "tropical", "island", "populous", "beaches", "rainforest"], 65],
    ["Philippines", "A tropical Southeast Asian archipelago.", ["asian", "developing", "tropical", "island", "english_speaking", "beaches", "populous"], 50],
    ["Malaysia", "A tropical Southeast Asian nation.", ["asian", "developing", "tropical", "beaches", "spicy_food", "rainforest"], 55],
    ["Singapore", "A tiny wealthy island city-state.", ["asian", "developed", "island", "small", "tech_advanced", "tropical", "english_speaking"], 55],
    ["Pakistan", "A populous South Asian nation.", ["asian", "developing", "populous", "mountainous", "spicy_food", "hot"], 50],
    ["Bangladesh", "A densely populated South Asian nation.", ["asian", "developing", "populous", "tropical", "spicy_food", "hot"], 45],
    ["Netherlands", "A small flat European nation.", ["european", "developed", "small", "english_speaking", "tech_advanced"], 65],
    ["Belgium", "A small European nation.", ["european", "developed", "small", "monarchy"], 55],
    ["Switzerland", "A wealthy mountainous European nation.", ["european", "developed", "mountainous", "landlocked", "tech_advanced", "cold"], 70],
    ["Austria", "A central European alpine nation.", ["european", "developed", "landlocked", "mountainous", "cold"], 50],
    ["Sweden", "A large Nordic European nation.", ["european", "developed", "cold", "tech_advanced", "monarchy"], 65],
    ["Norway", "A wealthy Nordic nation.", ["european", "developed", "cold", "mountainous", "oil_rich", "monarchy"], 60],
    ["Denmark", "A small Nordic nation.", ["european", "developed", "cold", "monarchy"], 55],
    ["Finland", "A Nordic European nation.", ["european", "developed", "cold", "tech_advanced"], 50],
    ["Poland", "A large Central European nation.", ["european", "developed", "populous", "cold"], 55],
    ["Ukraine", "A large Eastern European nation.", ["european", "developing", "large", "cold"], 50],
    ["Greece", "The cradle of Western civilization.", ["european", "developed", "ancient_place", "mediterranean", "island", "beaches", "hot"], 65],
    ["Portugal", "A southwestern European nation.", ["european", "developed", "mediterranean", "beaches", "hot"], 55],
    ["Ireland", "An island nation in NW Europe.", ["european", "developed", "island", "english_speaking", "cold"], 55],
    ["Iceland", "A volcanic island in the North Atlantic.", ["european", "developed", "island", "cold", "mountainous"], 40],
    ["Czech Republic", "A Central European nation.", ["european", "developed", "landlocked", "cold"], 50],
    ["Hungary", "A Central European nation.", ["european", "developed", "landlocked", "cold"], 45],
    ["Romania", "An Eastern European nation.", ["european", "developing", "cold", "mountainous"], 45],
    ["Cuba", "A Caribbean island nation.", ["american", "caribbean", "developing", "island", "tropical", "communist", "spanish_speaking", "beaches"], 45],
    ["Jamaica", "A Caribbean island nation.", ["american", "caribbean", "developing", "island", "tropical", "beaches", "english_speaking"], 40],
    ["Panama", "Home of the Panama Canal.", ["american", "developing", "tropical", "beaches", "spanish_speaking"], 35],
    ["Costa Rica", "A tropical Central American nation.", ["american", "developing", "tropical", "beaches", "spanish_speaking", "rainforest"], 45],
    ["Morocco", "A North African kingdom.", ["african", "developing", "arabic_speaking", "monarchy", "mountainous", "hot", "mediterranean"], 55],
    ["Tunisia", "A North African Mediterranean nation.", ["african", "developing", "arabic_speaking", "beaches", "ancient_place", "hot", "mediterranean"], 40],
    ["Algeria", "A large North African nation.", ["african", "developing", "arabic_speaking", "large", "desert", "hot"], 60],
    ["Libya", "A North African desert nation.", ["african", "developing", "arabic_speaking", "desert", "hot", "oil_rich"], 35],
    ["Sudan", "A large African nation.", ["african", "developing", "arabic_speaking", "desert", "hot", "large"], 35],
    ["Ethiopia", "An ancient East African nation.", ["african", "developing", "landlocked", "ancient_place", "mountainous", "hot"], 45],
    ["Tanzania", "An East African nation with Kilimanjaro.", ["african", "developing", "mountainous", "tropical", "hot"], 40],
    ["Uganda", "An East African nation.", ["african", "developing", "landlocked", "tropical", "hot"], 35],
    ["Ghana", "A West African nation.", ["african", "developing", "tropical", "english_speaking", "hot"], 40],
    ["Senegal", "A West African nation.", ["african", "developing", "french_speaking", "tropical", "beaches", "hot"], 35],
    ["Zimbabwe", "A southern African nation.", ["african", "developing", "landlocked", "english_speaking", "hot"], 30],
    ["Zambia", "A southern African nation.", ["african", "developing", "landlocked", "english_speaking", "tropical"], 30],
    ["Cambodia", "A Southeast Asian nation.", ["asian", "developing", "tropical", "ancient_place", "hot"], 35],
    ["Sri Lanka", "A tropical island nation south of India.", ["asian", "developing", "island", "tropical", "beaches", "spicy_food", "hot"], 40],
    ["Nepal", "Home of Mount Everest.", ["asian", "developing", "landlocked", "mountainous", "cold"], 40],
    ["Afghanistan", "A mountainous Central Asian nation.", ["asian", "developing", "landlocked", "mountainous", "hot"], 40],
    ["Kazakhstan", "A large Central Asian nation.", ["asian", "developing", "large", "landlocked", "cold"], 40],
    ["Uzbekistan", "A Central Asian nation on the Silk Road.", ["asian", "developing", "landlocked", "desert", "ancient_place", "hot"], 30],
    ["Qatar", "A wealthy Gulf state.", ["asian", "middle_east", "developed", "arabic_speaking", "oil_rich", "hot", "desert", "small", "monarchy"], 45],
    ["Kuwait", "A small wealthy Gulf state.", ["asian", "middle_east", "developed", "arabic_speaking", "oil_rich", "hot", "desert", "small", "monarchy"], 40],
    ["Oman", "A Gulf sultanate.", ["asian", "middle_east", "developing", "arabic_speaking", "desert", "oil_rich", "hot", "monarchy"], 35],
    ["Lebanon", "A small Mediterranean Middle Eastern nation.", ["asian", "middle_east", "developing", "arabic_speaking", "ancient_place", "mediterranean", "hot"], 40],
    ["Jordan", "A Middle Eastern kingdom.", ["asian", "middle_east", "developing", "arabic_speaking", "desert", "ancient_place", "hot", "monarchy"], 40],
    ["Yemen", "A southern Arabian Peninsula nation.", ["asian", "middle_east", "developing", "arabic_speaking", "desert", "hot"], 30],
    ["Syria", "A Middle Eastern nation.", ["asian", "middle_east", "developing", "arabic_speaking", "ancient_place", "desert", "hot"], 35],
    ["Uruguay", "A small South American nation.", ["american", "developing", "spanish_speaking", "southern_hemisphere", "beaches"], 35],
    ["Paraguay", "A landlocked South American nation.", ["american", "developing", "landlocked", "spanish_speaking", "southern_hemisphere", "tropical"], 25],
    ["Bolivia", "A landlocked South American nation.", ["american", "developing", "landlocked", "spanish_speaking", "mountainous", "tropical"], 30],
    ["Ecuador", "Home of the Galapagos Islands.", ["american", "developing", "spanish_speaking", "mountainous", "tropical", "ancient_place"], 35],
    ["Venezuela", "A tropical South American nation.", ["american", "developing", "spanish_speaking", "tropical", "oil_rich", "southern_hemisphere", "beaches"], 40],
    ["Croatia", "A Mediterranean European nation.", ["european", "developed", "mediterranean", "beaches", "ancient_place", "mountainous"], 50],
    ["Serbia", "A Balkan European nation.", ["european", "developing", "landlocked", "cold"], 35],
    ["Bulgaria", "A Balkan European nation.", ["european", "developing", "mountainous", "cold", "beaches"], 40],
    ["Albania", "A small Balkan nation.", ["european", "developing", "mountainous", "mediterranean", "beaches"], 30],
    ["Lithuania", "A Baltic European nation.", ["european", "developed", "small", "cold"], 30],
    ["Latvia", "A Baltic European nation.", ["european", "developed", "small", "cold"], 30],
    ["Estonia", "A Baltic European nation.", ["european", "developed", "small", "cold", "tech_advanced"], 30],
    ["Slovakia", "A Central European nation.", ["european", "developed", "landlocked", "mountainous", "cold"], 40],
    ["Slovenia", "A small Central European nation.", ["european", "developed", "small", "mountainous", "cold", "mediterranean"], 35],
    ["Luxembourg", "A tiny wealthy European nation.", ["european", "developed", "small", "landlocked", "tech_advanced"], 25],
    ["Malta", "A tiny Mediterranean island nation.", ["european", "developed", "small", "island", "mediterranean", "beaches", "ancient_place", "hot"], 30],
    ["Cyprus", "A Mediterranean island nation.", ["european", "developed", "island", "mediterranean", "beaches", "hot"], 35],
    ["Ivory Coast", "A West African nation.", ["african", "developing", "french_speaking", "tropical", "hot"], 25],
    ["Cameroon", "A Central African nation.", ["african", "developing", "french_speaking", "tropical", "hot"], 25],
    ["Angola", "A large Southern African nation.", ["african", "developing", "portuguese_speaking", "tropical", "hot"], 25],
    ["Mozambique", "A Southeast African nation.", ["african", "developing", "portuguese_speaking", "tropical", "beaches", "hot"], 25],
    ["Madagascar", "A large island off East Africa.", ["african", "developing", "island", "tropical", "hot"], 40],
    ["Mauritius", "A tropical island nation.", ["african", "developing", "island", "tropical", "beaches", "english_speaking", "hot"], 30],
    ["Namibia", "A dry Southern African nation.", ["african", "developing", "desert", "hot"], 30],
    ["Botswana", "A Southern African nation.", ["african", "developing", "landlocked", "desert", "hot"], 30],
    ["Mali", "A West African desert nation.", ["african", "developing", "landlocked", "desert", "french_speaking", "ancient_place", "hot"], 25],
    ["Bahrain", "A small Gulf island nation.", ["asian", "middle_east", "developed", "island", "arabic_speaking", "oil_rich", "hot", "desert", "small", "monarchy"], 30],
    ["Mongolia", "A large landlocked Asian nation.", ["asian", "developing", "large", "landlocked", "cold", "desert"], 30],
    ["Papua New Guinea", "A tropical island nation.", ["oceanian", "developing", "island", "tropical", "mountainous", "rainforest"], 25],
    ["Fiji", "A tropical Pacific island nation.", ["oceanian", "developing", "island", "tropical", "beaches", "english_speaking", "hot"], 35],
    ["Iceland", "A volcanic island nation.", ["european", "developed", "island", "cold", "mountainous"], 40],
    ["Haiti", "A Caribbean island nation.", ["american", "caribbean", "developing", "island", "tropical", "french_speaking", "hot"], 30],
    ["Dominican Republic", "A Caribbean nation.", ["american", "caribbean", "developing", "island", "tropical", "spanish_speaking", "beaches", "hot"], 35],
    ["Puerto Rico", "A Caribbean US territory.", ["american", "caribbean", "island", "tropical", "beaches", "spanish_speaking", "english_speaking", "hot"], 40],
    ["Bahamas", "A Caribbean island nation.", ["american", "caribbean", "developed", "island", "tropical", "beaches", "english_speaking", "hot"], 35],
    ["Barbados", "A Caribbean island nation.", ["american", "caribbean", "developed", "island", "tropical", "beaches", "english_speaking", "hot"], 30],
    ["Trinidad and Tobago", "A Caribbean nation.", ["american", "caribbean", "developing", "island", "tropical", "beaches", "english_speaking", "oil_rich", "hot"], 25],
    ["Guatemala", "A Central American nation.", ["american", "developing", "spanish_speaking", "tropical", "mountainous", "ancient_place", "hot"], 35],
    ["Honduras", "A Central American nation.", ["american", "developing", "spanish_speaking", "tropical", "mountainous", "hot"], 25],
    ["El Salvador", "A small Central American nation.", ["american", "developing", "spanish_speaking", "tropical", "small", "hot"], 25],
    ["Nicaragua", "A Central American nation.", ["american", "developing", "spanish_speaking", "tropical", "hot"], 25],
    ["Belize", "A small Central American nation.", ["american", "developing", "tropical", "english_speaking", "beaches", "rainforest", "hot"], 22],
    ["Liberia", "A West African nation.", ["african", "developing", "english_speaking", "tropical", "hot"], 25],
    ["Sierra Leone", "A West African nation.", ["african", "developing", "english_speaking", "tropical", "hot"], 25],
    ["Togo", "A West African nation.", ["african", "developing", "french_speaking", "tropical", "hot"], 25],
    ["Burkina Faso", "A landlocked West African nation.", ["african", "developing", "landlocked", "french_speaking", "desert", "hot"], 25],
    ["Niger", "A landlocked West African nation.", ["african", "developing", "landlocked", "french_speaking", "desert", "hot"], 25],
    ["Mauritania", "A dry West African nation.", ["african", "developing", "arabic_speaking", "desert", "hot"], 25],
    ["Somalia", "A Horn of Africa nation.", ["african", "developing", "arabic_speaking", "desert", "hot", "tropical"], 30],
    ["Eritrea", "A Horn of Africa nation.", ["african", "developing", "arabic_speaking", "hot", "desert"], 25],
    ["South Sudan", "The world's newest country.", ["african", "developing", "landlocked", "tropical", "hot"], 22],
    ["Rwanda", "A small East African nation.", ["african", "developing", "landlocked", "french_speaking", "mountainous", "tropical"], 35],
    ["Burundi", "A small East African nation.", ["african", "developing", "landlocked", "french_speaking", "tropical", "hot"], 22],
    ["Lesotho", "A small landlocked southern African kingdom.", ["african", "developing", "landlocked", "cold", "mountainous", "monarchy"], 22],
    ["Eswatini", "A small southern African kingdom.", ["african", "developing", "landlocked", "tropical", "monarchy", "hot"], 22],
    ["Djibouti", "A small Horn of Africa nation.", ["african", "developing", "arabic_speaking", "french_speaking", "desert", "hot", "small"], 22],
    ["Comoros", "A small Indian Ocean island nation.", ["african", "developing", "island", "tropical", "arabic_speaking", "hot", "small"], 20],
    ["Seychelles", "An Indian Ocean island nation.", ["african", "developing", "island", "tropical", "beaches", "small", "hot"], 25],
    ["Cabo Verde", "An Atlantic island nation.", ["african", "developing", "island", "tropical", "portuguese_speaking", "beaches", "hot"], 25],
    ["Sao Tome and Principe", "A tiny Atlantic island nation.", ["african", "developing", "island", "tropical", "portuguese_speaking", "hot", "small"], 15],
    ["Bhutan", "A Himalayan kingdom.", ["asian", "developing", "landlocked", "mountainous", "cold", "monarchy"], 25],
    ["Maldives", "A tropical island nation.", ["asian", "developing", "island", "tropical", "beaches", "hot", "small"], 35],
    ["Brunei", "A small wealthy Gulf sultanate.", ["asian", "developing", "oil_rich", "monarchy", "tropical", "hot", "small"], 25],
    ["Timor-Leste", "A small Southeast Asian nation.", ["asian", "developing", "tropical", "island", "hot", "small"], 15],
    ["Laos", "A landlocked Southeast Asian nation.", ["asian", "developing", "landlocked", "tropical", "communist", "hot"], 25],
    ["Myanmar", "A Southeast Asian nation.", ["asian", "developing", "tropical", "hot", "mountainous"], 35],
    ["Kyrgyzstan", "A Central Asian mountain nation.", ["asian", "developing", "landlocked", "mountainous", "cold"], 25],
    ["Tajikistan", "A Central Asian mountain nation.", ["asian", "developing", "landlocked", "mountainous", "cold"], 25],
    ["Turkmenistan", "A Central Asian desert nation.", ["asian", "developing", "landlocked", "desert", "hot"], 25],
    ["Armenia", "A Caucasus mountain nation.", ["european", "developing", "landlocked", "mountainous", "cold"], 35],
    ["Georgia", "A Caucasus nation.", ["european", "developing", "mountainous", "mediterranean", "cold"], 35],
    ["Azerbaijan", "A Caucasus nation.", ["asian", "developing", "oil_rich", "mountainous", "hot"], 35],
    ["Belarus", "An Eastern European nation.", ["european", "developing", "landlocked", "cold"], 35],
    ["Moldova", "A small Eastern European nation.", ["european", "developing", "landlocked", "small", "cold"], 25],
    ["Bosnia and Herzegovina", "A Balkan nation.", ["european", "developing", "mountainous", "cold"], 30],
    ["Montenegro", "A small Balkan nation.", ["european", "developing", "mountainous", "beaches", "mediterranean"], 25],
    ["North Macedonia", "A small Balkan nation.", ["european", "developing", "landlocked", "mountainous", "cold"], 25],
    ["Albania", "A Balkan nation.", ["european", "developing", "mountainous", "mediterranean", "beaches", "hot"], 30],
    ["Andorra", "A tiny Pyrenees principality.", ["european", "developed", "small", "landlocked", "mountainous", "cold"], 20],
    ["Liechtenstein", "A tiny Alpine principality.", ["european", "developed", "small", "landlocked", "mountainous", "cold", "monarchy"], 18],
    ["Monaco", "A tiny Mediterranean principality.", ["european", "developed", "small", "mediterranean", "beaches", "monarchy", "hot"], 25],
    ["San Marino", "A tiny European republic.", ["european", "developed", "small", "landlocked", "mediterranean", "hot"], 18],
    ["Vatican City", "The smallest country in the world.", ["european", "developed", "small", "landlocked", "mediterranean", "ancient_place", "hot"], 25],
    ["Solomon Islands", "A Pacific island nation.", ["oceanian", "developing", "island", "tropical", "english_speaking", "hot"], 18],
    ["Vanuatu", "A Pacific island nation.", ["oceanian", "developing", "island", "tropical", "beaches", "hot"], 18],
    ["Samoa", "A Pacific island nation.", ["oceanian", "developing", "island", "tropical", "beaches", "english_speaking", "hot"], 20],
    ["Tonga", "A Pacific island kingdom.", ["oceanian", "developing", "island", "tropical", "english_speaking", "monarchy", "hot"], 18],
    ["Kiribati", "A Pacific island nation.", ["oceanian", "developing", "island", "tropical", "english_speaking", "hot", "small"], 15],
    ["Marshall Islands", "A Pacific island nation.", ["oceanian", "developing", "island", "tropical", "english_speaking", "hot", "small"], 15],
    ["Micronesia", "A Pacific island nation.", ["oceanian", "developing", "island", "tropical", "english_speaking", "hot", "small"], 15],
    ["Palau", "A Pacific island nation.", ["oceanian", "developing", "island", "tropical", "beaches", "english_speaking", "hot", "small"], 15],
    ["Nauru", "A tiny Pacific island nation.", ["oceanian", "developing", "island", "tropical", "small", "english_speaking", "hot"], 12],
    ["Tuvalu", "A tiny Pacific island nation.", ["oceanian", "developing", "island", "tropical", "small", "english_speaking", "hot"], 12],
    ["Guyana", "A South American nation.", ["american", "developing", "tropical", "english_speaking", "rainforest", "southern_hemisphere", "hot"], 20],
    ["Suriname", "A South American nation.", ["american", "developing", "tropical", "dutch_speaking", "rainforest", "southern_hemisphere", "hot"], 18],
    ["Antigua and Barbuda", "A Caribbean island nation.", ["american", "caribbean", "developing", "island", "tropical", "beaches", "english_speaking", "hot", "small"], 20],
    ["Saint Lucia", "A Caribbean island nation.", ["american", "caribbean", "developing", "island", "tropical", "beaches", "english_speaking", "hot", "small"], 18],
    ["Saint Kitts and Nevis", "A Caribbean island nation.", ["american", "caribbean", "developing", "island", "tropical", "beaches", "english_speaking", "hot", "small"], 15],
    ["Saint Vincent and the Grenadines", "A Caribbean island nation.", ["american", "caribbean", "developing", "island", "tropical", "beaches", "english_speaking", "hot", "small"], 15],
    ["Grenada", "A Caribbean island nation.", ["american", "caribbean", "developing", "island", "tropical", "beaches", "english_speaking", "hot", "small"], 18],
    ["Dominica", "A Caribbean island nation.", ["american", "caribbean", "developing", "island", "tropical", "english_speaking", "hot", "small"], 20],
    ["Equatorial Guinea", "A small Central African nation.", ["african", "developing", "spanish_speaking", "tropical", "oil_rich", "hot"], 22],
    ["Gabon", "A Central African nation.", ["african", "developing", "french_speaking", "tropical", "rainforest", "oil_rich", "hot"], 22],
    ["Congo", "A Central African nation.", ["african", "developing", "french_speaking", "tropical", "rainforest", "hot"], 25],
    ["Democratic Republic of the Congo", "A large Central African nation.", ["african", "developing", "french_speaking", "large", "tropical", "rainforest", "populous", "hot"], 35],
    ["Central African Republic", "A landlocked Central African nation.", ["african", "developing", "landlocked", "french_speaking", "tropical", "hot"], 20],
    ["Chad", "A landlocked African nation.", ["african", "developing", "landlocked", "french_speaking", "desert", "hot"], 22],
    ["Guinea", "A West African nation.", ["african", "developing", "french_speaking", "tropical", "hot"], 22],
    ["Guinea-Bissau", "A West African nation.", ["african", "developing", "portuguese_speaking", "tropical", "hot"], 20],
    ["Gambia", "A small West African nation.", ["african", "developing", "english_speaking", "tropical", "small", "hot"], 20],
    ["Mauritius", "An Indian Ocean island nation.", ["african", "developing", "island", "tropical", "beaches", "english_speaking", "hot"], 30],
    ["Zambia", "A southern African nation.", ["african", "developing", "landlocked", "english_speaking", "tropical", "hot"], 30],
  ];

  console.log(`\nAdding ${countries.length} countries...`);
  for (const [name, desc, tags, pop] of countries) { await C(name, desc, tags, pop); }

  // === SPORTS (195+) ===
  const S = (name: string, desc: string, tags: string[], pop: number) => addEntity(name, desc, sportCat.id, ["sport", ...tags], pop);

  const sports: [string, string, string[], number][] = [
    ["Football (Soccer)", "The world's most popular sport.", ["team_sport", "ball_sport", "uses_ball", "outdoor_sport", "olympic", "popular_sport", "kicking", "field_sport"], 96],
    ["Basketball", "A team sport of hoops.", ["team_sport", "ball_sport", "uses_ball", "indoor_sport", "olympic", "popular_sport", "court_sport"], 92],
    ["American Football", "The NFL contact sport.", ["team_sport", "ball_sport", "uses_ball", "contact", "outdoor_sport", "field_sport", "popular_sport"], 88],
    ["Baseball", "America's pastime.", ["team_sport", "ball_sport", "uses_ball", "uses_bat", "outdoor_sport", "popular_sport"], 82],
    ["Cricket", "A bat-and-ball sport.", ["team_sport", "ball_sport", "uses_ball", "uses_bat", "outdoor_sport", "popular_sport"], 80],
    ["Volleyball", "A net sport of sets and spikes.", ["team_sport", "ball_sport", "uses_ball", "olympic", "net_sport", "court_sport", "indoor_sport", "outdoor_sport"], 78],
    ["Tennis", "A racket sport of aces.", ["racket_sport", "individual_sport", "uses_ball", "uses_racket", "olympic", "net_sport", "court_sport", "popular_sport"], 88],
    ["Table Tennis", "Ping pong.", ["racket_sport", "individual_sport", "uses_ball", "uses_racket", "indoor_sport", "olympic", "net_sport"], 65],
    ["Badminton", "A racket sport with a shuttlecock.", ["racket_sport", "individual_sport", "uses_shuttlecock", "uses_racket", "indoor_sport", "olympic", "net_sport", "court_sport"], 70],
    ["Boxing", "The sweet science of fist-fighting.", ["combat_sport", "individual_sport", "contact", "olympic", "popular_sport", "indoor_sport"], 84],
    ["Mixed Martial Arts (MMA)", "Mixed martial arts combat.", ["combat_sport", "individual_sport", "contact", "popular_sport"], 80],
    ["Judo", "A Japanese grappling martial art.", ["combat_sport", "individual_sport", "contact", "olympic", "grappling"], 65],
    ["Karate", "A Japanese striking martial art.", ["combat_sport", "individual_sport", "contact", "olympic", "striking"], 70],
    ["Taekwondo", "A Korean kicking martial art.", ["combat_sport", "individual_sport", "contact", "olympic", "kicking", "striking"], 65],
    ["Swimming", "Racing in water.", ["water_sport", "individual_sport", "olympic", "swimming", "indoor_sport", "endurance"], 85],
    ["Athletics (Track & Field)", "Running, jumping, and throwing.", ["individual_sport", "olympic", "outdoor_sport", "running", "jumping", "throwing", "endurance"], 80],
    ["Cycling", "Racing on bicycles.", ["individual_sport", "uses_bike", "outdoor_sport", "olympic", "racing_sport", "endurance"], 70],
    ["Golf", "A precision club sport.", ["individual_sport", "uses_ball", "outdoor_sport", "precision", "popular_sport"], 82],
    ["Ice Hockey", "Fast team sport on ice.", ["team_sport", "uses_puck", "uses_stick", "contact", "winter_sport", "ice_sport", "olympic", "skating", "indoor_sport", "popular_sport"], 80],
    ["Rugby", "A tough contact team sport.", ["team_sport", "uses_ball", "contact", "outdoor_sport", "olympic", "field_sport"], 70],
    ["Surfing", "Riding ocean waves.", ["water_sport", "individual_sport", "uses_board", "outdoor_sport", "olympic", "extreme_sport"], 70],
    ["Skiing (Alpine)", "Downhill skiing.", ["winter_sport", "individual_sport", "uses_skis", "outdoor_sport", "olympic", "snow_sport", "extreme_sport"], 65],
    ["Snowboarding", "Boarding on snow.", ["winter_sport", "individual_sport", "uses_board", "outdoor_sport", "olympic", "snow_sport", "extreme_sport"], 65],
    ["Figure Skating", "Artistic ice skating.", ["winter_sport", "individual_sport", "ice_sport", "skating", "olympic", "indoor_sport", "popular_sport"], 70],
    ["Gymnastics", "Artistic and acrobatic apparatus sport.", ["individual_sport", "olympic", "indoor_sport", "strength", "precision"], 65],
    ["Wrestling", "Grappling and pinning.", ["combat_sport", "individual_sport", "contact", "olympic", "grappling"], 65],
    ["Fencing", "Sword fighting sport.", ["combat_sport", "individual_sport", "olympic", "precision", "indoor_sport"], 50],
    ["Archery", "Target shooting with a bow.", ["individual_sport", "uses_bow", "olympic", "precision", "outdoor_sport", "target_sport"], 55],
    ["Shooting (Sport)", "Target shooting.", ["individual_sport", "uses_gun", "olympic", "precision", "indoor_sport", "outdoor_sport", "target_sport"], 50],
    ["Rowing", "Racing in boats.", ["water_sport", "uses_boat", "olympic", "endurance", "outdoor_sport", "strength"], 55],
    ["Sailing", "Wind-powered water racing.", ["water_sport", "uses_boat", "olympic", "outdoor_sport", "precision"], 60],
    ["Canoeing", "Paddling in canoes.", ["water_sport", "uses_boat", "olympic", "outdoor_sport", "endurance"], 50],
    ["Equestrianism", "Horse riding sport.", ["individual_sport", "uses_horse", "olympic", "riding", "precision", "outdoor_sport"], 50],
    ["Weightlifting", "Lifting heavy weights.", ["individual_sport", "olympic", "strength", "indoor_sport"], 55],
    ["Handball", "Team handball.", ["team_sport", "uses_ball", "indoor_sport", "olympic", "court_sport"], 55],
    ["Field Hockey", "Hockey on grass.", ["team_sport", "uses_ball", "uses_stick", "outdoor_sport", "olympic", "field_sport"], 55],
    ["Water Polo", "Team sport in water.", ["team_sport", "uses_ball", "water_sport", "olympic", "contact", "swimming"], 50],
    ["Bobsleigh", "Team sled racing on ice.", ["winter_sport", "team_sport", "ice_sport", "olympic", "racing_sport", "dangerous"], 50],
    ["Luge", "Solo sled racing on ice.", ["winter_sport", "individual_sport", "ice_sport", "olympic", "racing_sport", "dangerous"], 45],
    ["Skeleton", "Head-first sled racing.", ["winter_sport", "individual_sport", "ice_sport", "olympic", "racing_sport", "dangerous"], 40],
    ["Curling", "Sliding stones on ice.", ["winter_sport", "team_sport", "ice_sport", "olympic", "precision", "indoor_sport"], 50],
    ["Biathlon", "Skiing and shooting.", ["winter_sport", "individual_sport", "uses_skis", "uses_gun", "olympic", "outdoor_sport", "endurance", "shooting", "snow_sport"], 45],
    ["Ski Jumping", "Flying off a ramp on skis.", ["winter_sport", "individual_sport", "uses_skis", "olympic", "snow_sport", "extreme_sport", "jumping"], 55],
    ["Triathlon", "Swim, bike, run.", ["individual_sport", "olympic", "endurance", "swimming", "uses_bike", "running", "outdoor_sport", "water_sport"], 60],
    ["Marathon", "Long-distance running.", ["individual_sport", "olympic", "endurance", "running", "outdoor_sport"], 75],
    ["Diving", "Acrobatic diving into water.", ["water_sport", "individual_sport", "olympic", "jumping", "indoor_sport", "precision"], 60],
    ["Skateboarding", "Tricks on a skateboard.", ["individual_sport", "uses_board", "outdoor_sport", "olympic", "extreme_sport", "popular_sport"], 65],
    ["Climbing", "Competitive climbing.", ["individual_sport", "outdoor_sport", "olympic", "strength", "endurance", "extreme_sport"], 60],
    ["Squash", "Indoor racket sport.", ["racket_sport", "individual_sport", "uses_ball", "uses_racket", "indoor_sport", "popular_sport"], 55],
    ["Darts", "Throwing darts at a board.", ["individual_sport", "indoor_sport", "precision", "popular_sport", "throwing"], 60],
    ["Billiards", "Potting balls on a table.", ["individual_sport", "indoor_sport", "uses_cue", "precision", "popular_sport"], 60],
    ["Bowling (Ten-pin)", "Rolling a ball at pins.", ["individual_sport", "indoor_sport", "uses_ball", "precision", "popular_sport"], 65],
    ["Chess", "The royal board game.", ["individual_sport", "indoor_sport", "popular_sport", "precision"], 75],
    ["Polo", "Team sport on horseback.", ["team_sport", "uses_ball", "uses_horse", "outdoor_sport", "riding", "field_sport"], 40],
    ["Beach Volleyball", "Volleyball on sand.", ["team_sport", "uses_ball", "outdoor_sport", "olympic", "net_sport", "popular_sport"], 60],
    ["Netball", "Team sport similar to basketball.", ["team_sport", "uses_ball", "outdoor_sport", "court_sport", "net_sport"], 45],
    ["Lacrosse", "Team sport with sticks and a ball.", ["team_sport", "uses_ball", "uses_stick", "contact", "outdoor_sport", "field_sport"], 50],
    ["Auto Racing", "Car racing.", ["motorsport", "individual_sport", "uses_vehicle", "outdoor_sport", "racing_sport", "dangerous", "popular_sport"], 70],
    ["Motorcycle Racing", "Racing on motorcycles.", ["motorsport", "individual_sport", "uses_vehicle", "outdoor_sport", "racing_sport", "dangerous"], 60],
    ["Motocross", "Off-road motorcycle racing.", ["motorsport", "individual_sport", "uses_vehicle", "outdoor_sport", "racing_sport", "extreme_sport", "dangerous", "jumping"], 55],
    ["Horse Racing", "Racing on horseback.", ["racing_sport", "uses_horse", "outdoor_sport", "riding", "popular_sport"], 60],
    ["Marathon Swimming", "Long-distance open water swimming.", ["water_sport", "individual_sport", "olympic", "endurance", "swimming", "outdoor_sport"], 40],
    ["Synchronized Swimming", "Artistic team swimming.", ["water_sport", "team_sport", "olympic", "swimming", "indoor_sport", "precision"], 45],
    ["Sprint (Running)", "Short-distance running.", ["individual_sport", "olympic", "running", "outdoor_sport", "very_fast"], 80],
    ["Hurdles", "Running and jumping over barriers.", ["individual_sport", "olympic", "running", "jumping", "outdoor_sport"], 50],
    ["Long Jump", "Jumping for distance.", ["individual_sport", "olympic", "jumping", "outdoor_sport", "running"], 50],
    ["High Jump", "Jumping over a bar.", ["individual_sport", "olympic", "jumping", "outdoor_sport", "running"], 45],
    ["Pole Vault", "Jumping with a pole.", ["individual_sport", "olympic", "jumping", "outdoor_sport", "extreme_sport"], 40],
    ["Discus Throw", "Throwing a disc.", ["individual_sport", "olympic", "throwing", "outdoor_sport", "strength"], 40],
    ["Javelin Throw", "Throwing a spear.", ["individual_sport", "olympic", "throwing", "outdoor_sport", "strength"], 40],
    ["Shot Put", "Throwing a heavy ball.", ["individual_sport", "olympic", "throwing", "outdoor_sport", "strength"], 40],
    ["Cross-Country Skiing", "Endurance skiing.", ["winter_sport", "individual_sport", "uses_skis", "olympic", "endurance", "snow_sport", "outdoor_sport"], 50],
    ["Freestyle Skiing", "Acrobatic skiing.", ["winter_sport", "individual_sport", "uses_skis", "olympic", "snow_sport", "extreme_sport", "jumping", "tricks"], 50],
    ["Speed Skating", "Racing on ice skates.", ["winter_sport", "individual_sport", "ice_sport", "skating", "olympic", "racing_sport", "indoor_sport"], 50],
    ["Ice Dancing", "Artistic ice dancing in pairs.", ["winter_sport", "team_sport", "ice_sport", "skating", "olympic", "indoor_sport", "precision"], 45],
    ["Bandy", "Hockey on a large ice field.", ["winter_sport", "team_sport", "uses_ball", "uses_stick", "ice_sport", "skating", "outdoor_sport"], 25],
    ["Floorball", "Indoor hockey.", ["team_sport", "uses_ball", "uses_stick", "indoor_sport", "court_sport"], 30],
    ["Racquetball", "Indoor racket sport.", ["racket_sport", "individual_sport", "uses_ball", "uses_racket", "indoor_sport"], 40],
    ["Squash", "Indoor racket sport against a wall.", ["racket_sport", "individual_sport", "uses_ball", "uses_racket", "indoor_sport"], 55],
    ["Hurling", "Fast Irish field sport.", ["team_sport", "uses_ball", "uses_stick", "contact", "outdoor_sport", "field_sport"], 30],
    ["Australian Rules Football", "Aussie rules football.", ["team_sport", "uses_ball", "contact", "outdoor_sport", "field_sport", "kicking"], 50],
    ["Gaelic Football", "Irish field sport.", ["team_sport", "uses_ball", "contact", "outdoor_sport", "field_sport", "kicking"], 35],
    ["Sumo", "Japanese wrestling.", ["combat_sport", "individual_sport", "contact", "grappling", "indoor_sport"], 50],
    ["Muay Thai", "Thai kickboxing.", ["combat_sport", "individual_sport", "contact", "striking", "kicking"], 60],
    ["Kickboxing", "Boxing with kicks.", ["combat_sport", "individual_sport", "contact", "striking", "kicking"], 60],
    ["Brazilian Jiu-Jitsu", "Ground fighting.", ["combat_sport", "individual_sport", "contact", "grappling"], 55],
    ["Krav Maga", "Israeli self-defense.", ["combat_sport", "individual_sport", "contact", "striking"], 40],
    ["Parkour", "Urban running and jumping.", ["individual_sport", "outdoor_sport", "running", "jumping", "extreme_sport"], 50],
    ["Ultimate Frisbee", "Team sport with a disc.", ["team_sport", "uses_ball", "outdoor_sport", "running", "jumping"], 45],
    ["Kabaddi", "South Asian contact team sport.", ["team_sport", "contact", "indoor_sport", "popular_sport"], 40],
    ["Sepak Takraw", "Southeast Asian kick volleyball.", ["team_sport", "uses_ball", "kicking", "net_sport", "outdoor_sport"], 30],
    ["Cricket (T20)", "Fast-paced cricket.", ["team_sport", "uses_ball", "uses_bat", "outdoor_sport", "popular_sport"], 75],
    ["Badminton (Doubles)", "Team badminton.", ["racket_sport", "team_sport", "uses_shuttlecock", "uses_racket", "indoor_sport", "net_sport"], 55],
    ["Roller Derby", "Team roller skating sport.", ["team_sport", "contact", "skating", "indoor_sport", "racing_sport"], 30],
    ["Water Skiing", "Skiing on water behind a boat.", ["water_sport", "individual_sport", "outdoor_sport", "extreme_sport"], 40],
    ["Wakeboarding", "Boarding on water behind a boat.", ["water_sport", "individual_sport", "uses_board", "outdoor_sport", "extreme_sport"], 45],
    ["Kiteboarding", "Boarding with a kite.", ["water_sport", "individual_sport", "uses_board", "outdoor_sport", "extreme_sport"], 45],
    ["Windsurfing", "Boarding with a sail.", ["water_sport", "individual_sport", "uses_board", "outdoor_sport"], 45],
    ["Cliff Diving", "Diving from cliffs.", ["water_sport", "individual_sport", "outdoor_sport", "extreme_sport", "jumping", "dangerous"], 35],
    ["Bungee Jumping", "Jumping with an elastic cord.", ["individual_sport", "outdoor_sport", "extreme_sport", "jumping", "dangerous"], 40],
    ["Skydiving", "Jumping from airplanes.", ["individual_sport", "outdoor_sport", "extreme_sport", "dangerous"], 45],
    ["Rock Climbing", "Climbing rock walls.", ["individual_sport", "outdoor_sport", "strength", "extreme_sport", "dangerous"], 60],
    ["Mountain Biking", "Off-road cycling.", ["individual_sport", "uses_bike", "outdoor_sport", "extreme_sport", "racing_sport"], 55],
    ["BMX", "Bicycle motocross.", ["individual_sport", "uses_bike", "outdoor_sport", "extreme_sport", "racing_sport", "jumping", "tricks"], 50],
    ["Fishing (Sport)", "Competitive fishing.", ["individual_sport", "outdoor_sport", "water_sport", "precision"], 65],
    ["Hiking", "Long-distance walking in nature.", ["individual_sport", "outdoor_sport", "endurance"], 70],
    ["Yoga", "Mind-body practice.", ["individual_sport", "indoor_sport", "precision", "flexibility_sport"], 75],
    ["Pilates", "Core strength training.", ["individual_sport", "indoor_sport", "strength", "flexibility_sport"], 50],
    ["CrossFit", "High-intensity fitness.", ["individual_sport", "indoor_sport", "strength", "endurance", "extreme_sport"], 55],
    ["Bodybuilding", "Muscle building competition.", ["individual_sport", "indoor_sport", "strength"], 55],
    ["Powerlifting", "Squat, bench, deadlift.", ["individual_sport", "indoor_sport", "strength"], 50],
    ["Calisthenics", "Bodyweight fitness.", ["individual_sport", "outdoor_sport", "strength"], 40],
    ["Obstacle Course Racing", "Mud runs and obstacle courses.", ["individual_sport", "outdoor_sport", "endurance", "strength", "extreme_sport"], 40],
    ["Orienteering", "Navigation and running.", ["individual_sport", "outdoor_sport", "endurance", "precision", "running"], 30],
    ["Paintball", "Team combat with paint markers.", ["team_sport", "outdoor_sport", "uses_gun", "shooting", "contact", "extreme_sport"], 50],
    ["Airsoft", "Team combat with replica guns.", ["team_sport", "outdoor_sport", "uses_gun", "shooting", "contact", "extreme_sport"], 40],
    ["Cheerleading", "Team acrobatics and stunts.", ["team_sport", "indoor_sport", "strength", "jumping", "extreme_sport", "dangerous"], 45],
    ["Marching Band", "Musical marching sport.", ["team_sport", "outdoor_sport", "precision"], 30],
    ["Drone Racing", "First-person drone racing.", ["individual_sport", "uses_vehicle", "outdoor_sport", "racing_sport", "extreme_sport"], 25],
    ["Esports (Gaming)", "Competitive video gaming.", ["individual_sport", "team_sport", "indoor_sport", "popular_sport", "precision"], 75],
    ["Dog Sled Racing", "Racing with dog teams.", ["winter_sport", "individual_sport", "outdoor_sport", "snow_sport", "endurance", "racing_sport"], 30],
    ["Speedcubing", "Rubik's cube solving.", ["individual_sport", "indoor_sport", "precision"], 35],
    ["Tug of War", "Team rope pulling.", ["team_sport", "strength", "outdoor_sport", "uses_rope"], 30],
    ["Croquet", "Lawn sport with mallets.", ["individual_sport", "uses_ball", "outdoor_sport", "precision"], 25],
    ["Bocce", "Italian ball rolling.", ["individual_sport", "uses_ball", "outdoor_sport", "precision"], 30],
    ["Pétanque", "French boules.", ["individual_sport", "uses_ball", "outdoor_sport", "precision"], 25],
    ["Dodgeball", "Team sport of throwing and dodging.", ["team_sport", "uses_ball", "indoor_sport", "outdoor_sport", "throwing", "contact"], 45],
    ["Kickball", "Team sport combining soccer and baseball.", ["team_sport", "uses_ball", "outdoor_sport", "kicking", "field_sport"], 35],
    ["Wiffleball", "Backyard baseball variant.", ["team_sport", "uses_ball", "uses_bat", "outdoor_sport"], 25],
    ["Disc Golf", "Golf with frisbees.", ["individual_sport", "uses_ball", "outdoor_sport", "precision"], 35],
    ["Roller Skating", "Skating on roller skates.", ["individual_sport", "skating", "indoor_sport", "outdoor_sport", "racing_sport"], 40],
    ["Inline Skating", "Skating on inline skates.", ["individual_sport", "skating", "outdoor_sport", "racing_sport"], 35],
    ["Ice Climbing", "Climbing frozen waterfalls.", ["winter_sport", "individual_sport", "ice_sport", "outdoor_sport", "extreme_sport", "dangerous", "strength"], 25],
    ["Snowmobiling", "Racing snowmobiles.", ["winter_sport", "individual_sport", "uses_vehicle", "snow_sport", "outdoor_sport", "extreme_sport"], 35],
    ["Sandboarding", "Boarding on sand dunes.", ["individual_sport", "uses_board", "outdoor_sport", "extreme_sport"], 30],
    ["Hang Gliding", "Gliding with a wing.", ["individual_sport", "outdoor_sport", "extreme_sport", "dangerous"], 25],
    ["Paragliding", "Gliding with a parachute.", ["individual_sport", "outdoor_sport", "extreme_sport", "dangerous"], 30],
    ["Scuba Diving", "Underwater diving.", ["water_sport", "individual_sport", "outdoor_sport", "extreme_sport"], 50],
    ["Snorkeling", "Surface underwater swimming.", ["water_sport", "individual_sport", "outdoor_sport", "swimming"], 45],
    ["Kayaking", "Paddling in a kayak.", ["water_sport", "individual_sport", "uses_boat", "outdoor_sport", "endurance", "extreme_sport"], 45],
    ["Rafting", "White water rafting.", ["water_sport", "team_sport", "uses_boat", "outdoor_sport", "extreme_sport", "dangerous"], 40],
    ["Paddleboarding", "Standing on a board and paddling.", ["water_sport", "individual_sport", "uses_board", "outdoor_sport", "endurance"], 40],
    ["Bodyboarding", "Riding waves on a bodyboard.", ["water_sport", "individual_sport", "uses_board", "outdoor_sport", "extreme_sport"], 35],
    ["Freediving", "Diving without equipment.", ["water_sport", "individual_sport", "outdoor_sport", "extreme_sport", "dangerous", "swimming"], 30],
    ["Underwater Hockey", "Hockey played underwater.", ["water_sport", "team_sport", "uses_stick", "uses_puck", "swimming", "indoor_sport"], 20],
    ["Trampoline", "Jumping on a trampoline.", ["individual_sport", "indoor_sport", "olympic", "jumping", "acrobatic_sport", "tricks"], 40],
    ["Double Dutch", "Jump rope team sport.", ["team_sport", "individual_sport", "uses_rope", "jumping", "indoor_sport", "outdoor_sport"], 30],
    ["Jump Rope", "Solo rope jumping.", ["individual_sport", "uses_rope", "jumping", "indoor_sport", "outdoor_sport", "endurance"], 40],
    ["Hula Hoop", "Spinning a hoop.", ["individual_sport", "indoor_sport", "precision"], 25],
    ["Juggling", "Tossing objects.", ["individual_sport", "indoor_sport", "precision", "throwing"], 25],
    ["Yo-yo", "String and spool toy sport.", ["individual_sport", "indoor_sport", "precision"], 25],
    ["Kendama", "Japanese cup-and-ball.", ["individual_sport", "indoor_sport", "precision"], 15],
    ["Kite Flying (Sport)", "Competitive kite flying.", ["individual_sport", "outdoor_sport", "precision"], 20],
    ["Model Aviation", "Flying model aircraft.", ["individual_sport", "outdoor_sport", "uses_vehicle", "precision"], 20],
    ["Ham Radio Contesting", "Amateur radio competition.", ["individual_sport", "indoor_sport", "precision"], 15],
    ["Chess Boxing", "Alternating chess and boxing.", ["individual_sport", "combat_sport", "contact", "indoor_sport", "precision"], 25],
    ["Footgolf", "Golf played by kicking a ball.", ["individual_sport", "uses_ball", "outdoor_sport", "kicking", "precision"], 25],
    ["Slacklining", "Walking on a slackline.", ["individual_sport", "outdoor_sport", "extreme_sport", "balance_sport"], 25],
    ["Parkour", "Urban obstacle running.", ["individual_sport", "outdoor_sport", "running", "jumping", "extreme_sport"], 50],
    ["Freerunning", "Acrobatic urban running.", ["individual_sport", "outdoor_sport", "running", "jumping", "extreme_sport", "tricks"], 40],
    ["Bossaball", "Volleyball on inflatables.", ["team_sport", "uses_ball", "outdoor_sport", "net_sport", "jumping", "kicking"], 15],
    ["Rounders", "British bat-and-ball sport.", ["team_sport", "uses_ball", "uses_bat", "outdoor_sport", "field_sport"], 20],
    ["Stoolball", "Traditional Sussex sport.", ["team_sport", "uses_ball", "uses_bat", "outdoor_sport"], 10],
    ["Knattleikr", "Viking ball sport.", ["team_sport", "uses_ball", "contact", "outdoor_sport"], 5],
    ["Calcio Storico", "Medieval Florentine football.", ["team_sport", "uses_ball", "contact", "outdoor_sport", "dangerous"], 10],
    ["Cycle Polo", "Polo on bicycles.", ["team_sport", "uses_ball", "uses_bike", "uses_stick", "outdoor_sport"], 10],
    ["Canoe Polo", "Polo in canoes.", ["team_sport", "uses_ball", "water_sport", "uses_boat", "outdoor_sport"], 15],
    ["Underwater Rugby", "Rugby underwater.", ["water_sport", "team_sport", "uses_ball", "contact", "swimming", "indoor_sport"], 15],
    ["Fistball", "Volleyball with fists.", ["team_sport", "uses_ball", "outdoor_sport", "net_sport", "field_sport"], 15],
    ["Korfball", "Dutch mixed-gender basketball.", ["team_sport", "uses_ball", "indoor_sport", "court_sport", "net_sport"], 20],
    ["Ringette", "Ice sport with a ring.", ["team_sport", "uses_stick", "ice_sport", "skating", "winter_sport", "indoor_sport"], 20],
    ["Bocce (Volo)", "French boules variant.", ["individual_sport", "uses_ball", "outdoor_sport", "precision"], 15],
    ["Racketlon", "Four racket sports combined.", ["individual_sport", "uses_racket", "indoor_sport", "precision"], 15],
    ["Snowshoeing", "Walking on snow with snowshoes.", ["winter_sport", "individual_sport", "outdoor_sport", "snow_sport", "endurance"], 25],
    ["Ice Speedway", "Motorcycle racing on ice.", ["motorsport", "individual_sport", "uses_vehicle", "ice_sport", "winter_sport", "racing_sport", "dangerous"], 15],
    ["Snowkiting", "Kite skiing.", ["winter_sport", "individual_sport", "uses_skis", "outdoor_sport", "snow_sport", "extreme_sport"], 15],
    ["Skibobbing", "Biking on snow.", ["winter_sport", "individual_sport", "uses_bike", "outdoor_sport", "snow_sport", "extreme_sport"], 10],
  ];

  console.log(`\nAdding ${sports.length} sports...`);
  for (const [name, desc, tags, pop] of sports) { await S(name, desc, tags, pop); }

  // Final counts
  const [aCount, cCount, sCount] = await Promise.all([
    db.entity.count({ where: { categoryId: animalCat.id, isActive: true } }),
    db.entity.count({ where: { categoryId: countryCat.id, isActive: true } }),
    db.entity.count({ where: { categoryId: sportCat.id, isActive: true } }),
  ]);
  const [aQ, cQ, sQ] = await Promise.all([
    db.question.count({ where: { categoryId: animalCat.id, isActive: true } }),
    db.question.count({ where: { categoryId: countryCat.id, isActive: true } }),
    db.question.count({ where: { categoryId: sportCat.id, isActive: true } }),
  ]);
  console.log(`\n=== FINAL ===\n  Animals: ${aCount} entities, ${aQ} questions\n  Countries: ${cCount} entities, ${cQ} questions\n  Sports: ${sCount} entities, ${sQ} questions`);

  await db.$disconnect();
}

main().catch(e => { console.error(e); process.exit(1); });
